server:
  port: 7900
spring:
  application:
    name: microservice-consumer-movie-ribbon
eureka:
  client:
    service-url:
      defaultZone: http://liuxun:123456@localhost:8761/eureka # 声明注册中心地址
  instance:
    prefer-ip-address: true #显示IP地址
microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule